In [85]:
import numpy as np
#!pip install jupyterthemes

In [132]:
from jupyterthemes import get_themes
import jupyterthemes as jt
from jupyterthemes.stylefx import set_nb_theme
set_nb_theme('monokai')

#If you dont want this theme, just comment all the lines of code in this block, save and then reload the page 

In [168]:
!jt -l
'''Available Themes: 
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl'''

Available Themes: 
   chesterish
   grade3
   gruvboxd
   gruvboxl
   monokai
   oceans16
   onedork
   solarizedd
   solarizedl


In [1]:
!jt -r

Reset css and font defaults in:
C:\Users\seeth\.jupyter\custom &
C:\Users\seeth\AppData\Roaming\jupyter\nbextensions


In [196]:
dir(np) #All methods in numpy

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


### 1-D Array

In [31]:
arr_1d = np.array([1,2,3,4,5])
arr_1d
print("Dimension:",arr_1d.ndim)
print("Shape:",arr_1d.shape)

Dimension: 1
Shape: (5,)


### 2-D Array

In [24]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print("Dimension:",arr_2d.ndim)
print("Shape:",arr_2d.shape)

[[1 2 3]
 [4 5 6]]
Dimension: 2
Shape: (2, 3)


### 3-D Array

In [41]:
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(arr_3d)
print("Dimension:",arr_3d.ndim)
print("Shape:",arr_3d.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimension: 3
Shape: (3, 2, 2)


### Converting array to different dimensions

In [42]:
con_arr_1d_to_3d = np.array([1,2,3,4,5],ndmin = 3) #1d
print(con_arr_1d_to_3d,'\n')
con_arr_3d_to_1d = np.array([[[1,2,3],[4,5,6]]],ndmin = 1) #3d (Cannot degrade)
print(con_arr_3d_to_1d)

[[[1 2 3 4 5]]] 

[[[1 2 3]
  [4 5 6]]]


### Reshaping
#### Using reshape one can change 3d to 1d where in ndmin it is not possible and this concept is called as flattening.

In [72]:
arr_1d_reshape = arr_1d.reshape(5,1) #5 rows and 1 column
print(arr_1d_reshape)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [71]:
arr_2d_reshape = arr_2d.reshape(1,6) #1 row and 6 column
print(arr_2d_reshape,'\n')
arr_2d_reshape1 = arr_2d.reshape(2,3)
print(arr_2d_reshape1)

[[1 2 3 4 5 6]] 

[[1 2 3]
 [4 5 6]]


In [73]:
arr_3d_reshape = arr_3d.reshape(1,4,3) #1 row and 4 column and number of elements inside
print(arr_3d_reshape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [76]:
#Flattening
flat = np.array([[1,2,3],[4,5,6]])
print(flat.reshape(-1))

[1 2 3 4 5 6]


### Arange in numpy

In [87]:
array = np.arange(1,10,2)
print(array,'\n')
array_2d = np.arange(1,10,2)
print(array_2d.reshape(1,5),'\n')
array_3d = np.arange(1,10,2)
print(array_3d.reshape(1,5,1))

[1 3 5 7 9] 

[[1 3 5 7 9]] 

[[[1]
  [3]
  [5]
  [7]
  [9]]]


### Zeros in numpy

In [96]:
array_zero = np.zeros([3,3])#Square or normal bracket should be used
print(array_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Ones in numpy

In [108]:
array_ones = np.ones((3,3))
print(array_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Empty in numpy

In [109]:
array_empty = np.empty((2,2))
print(array_empty)

[[4.24399158e-314 8.48798317e-314]
 [1.27319747e-313 1.69759663e-313]]


### Full in numpy

In [114]:
array_full = np.full((3,3),4)
print(array_full)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [118]:
array_full1 = np.full((3,3),'S')
print(array_full1)

[['S' 'S' 'S']
 ['S' 'S' 'S']
 ['S' 'S' 'S']]


### Eye in numpy

In [122]:
array_eye = np.eye(3,3)
print(array_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Linspace in numpy

In [129]:
array_lin = np.linspace(0,10,10)
print(array_lin)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


### Random in numpy

In [136]:
array_random = np.random.random((3,3))
print(array_random,'\n')
array_randint = np.random.randint(0,10,5)
print(array_randint)

[[0.08695509 0.77713847 0.68843618]
 [0.12442458 0.06846545 0.21233237]
 [0.40199284 0.93713959 0.43016881]] 

[3 9 7 1 6]


### Indexing and slicing in numpy

In [186]:
#Integer and boolean array indexing
#Integer array indexing:
a = np.arange(1,20,2)
print("Array",a,'\n')
index = a[np.array([2,3,4])] #Passing indexing position as numbers in array format
print("Index:",index)

#Another method0
index_a = ("Another method 0",a[0])
print("Another method1:",index_a)

#Another method1
lis = [0,1,2]
print("Another method0",a[lis])

Array [ 1  3  5  7  9 11 13 15 17 19] 

Index: [5 7 9]
Another method1: ('Another method 0', 1)
Another method0 [1 3 5]


In [188]:
#Boolean array indexing:
r = np.array([1,2,3,4,5]) #0 0 0 1 0 or (False False False  True False)
print(r == 4)

[False False False  True False]


In [192]:
#Slicing
q = np.arange(1,20)
print(q)
#From 2nd position to before 5th position but not 5th position i.e from 3 to before 6-->5
print("After slicing:",q[2:5])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
After slicing: [3 4 5]


### Arithmetic Operations

+ Add,
+ Subtract,
+ Multiply,
+ Divide,
+ Reciprocal,
+ Mod,
+ Power.


In [234]:
x = np.array([10,20,30,40,50])
z = np.array([2.0,4.0,5.0,8.0,9.0]) #Float values
print("Addition:",np.add(x,z),'\n')
print("Subtraction:",np.subtract(x,z),'\n')
print("Multiplication:",np.multiply(x,z),'\n')
print("Division",np.divide(x,z),'\n')
print("Reciprocal:",np.reciprocal(z),'\n') #Pass the value in float
print("Mod:",np.mod(x,z),'\n')
print("Power:",np.power(2,2),'\n') #Using large numbers can result in bigger value, so simply 2 pow 2

Addition: [12. 24. 35. 48. 59.] 

Subtraction: [ 8. 16. 25. 32. 41.] 

Multiplication: [ 20.  80. 150. 320. 450.] 

Division [5.         5.         6.         5.         5.55555556] 

Reciprocal: [0.5        0.25       0.2        0.125      0.11111111] 

Mod: [0. 0. 0. 0. 5.] 

Power: 4 



### Ones_like, zeros_like, full_like

In [6]:
s = np.arange(15)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
np.ones_like(s)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
np.zeros_like(s)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.full_like(s,4)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

### Problem 1

In [16]:
#declare 2 variables a,b (2 array)
#a --> sequence (from 0 to 12)
#b --> sequence (from 13 to 24)
#reshape b
#a,b with addition, multi then, --> reciprocal

In [86]:
a = np.arange(12)
#x = np.float64
b = np.arange(13,25, dtype = np.float64)
b1 = b.reshape(1,12)
b1

array([[13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.]])

In [87]:
np.add(a,b1)

array([[13., 15., 17., 19., 21., 23., 25., 27., 29., 31., 33., 35.]])

In [88]:
np.multiply(a,b1)

array([[  0.,  14.,  30.,  48.,  68.,  90., 114., 140., 168., 198., 230.,
        264.]])

In [89]:
np.reciprocal(b1)

array([[0.07692308, 0.07142857, 0.06666667, 0.0625    , 0.05882353,
        0.05555556, 0.05263158, 0.05      , 0.04761905, 0.04545455,
        0.04347826, 0.04166667]])

### Matrix Operations
+ Transpose,
+ VSplit,
+ HSplit,
+ Concatenate,
+ VStack,
+ HStack

In [101]:
#1-D --> No need to mention axis
#2-D --> Need to mention axis (0,1)
#3-D --> Need to mention axis (0,1,2)
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a,'\n')
print(a.transpose())

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [112]:
np.vsplit(a, 2)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [114]:
np.hsplit(a, 3)

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [125]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
a = (np.concatenate((arr1,arr2), axis = 0))
print(a,'\n')
b = (np.concatenate((arr1,arr2), axis = 1))
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]]


In [141]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
b = np.array([[[100,110],[111,122]],[[122,222],[113,333]],[[114,444],[115,555]]])
a1 = (np.concatenate((a,b), axis = 0))
print(a1,'\n','\n')
b1 = (np.concatenate((a,b), axis = 1))
print(b1,'\n','\n')
c1 = (np.concatenate((a,b), axis = 2))
print(c1)

[[[  1   2]
  [  3   4]]

 [[  5   6]
  [  7   8]]

 [[  9  10]
  [ 11  12]]

 [[100 110]
  [111 122]]

 [[122 222]
  [113 333]]

 [[114 444]
  [115 555]]] 
 

[[[  1   2]
  [  3   4]
  [100 110]
  [111 122]]

 [[  5   6]
  [  7   8]
  [122 222]
  [113 333]]

 [[  9  10]
  [ 11  12]
  [114 444]
  [115 555]]] 
 

[[[  1   2 100 110]
  [  3   4 111 122]]

 [[  5   6 122 222]
  [  7   8 113 333]]

 [[  9  10 114 444]
  [ 11  12 115 555]]]


In [154]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print(np.vstack((a,b,c)),'\n')
print(np.hstack((a,b,c)))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9]


### Mathematical Functions
 + Trigonometric, 
 + Hyperbolic, 
 + Rounding, 
 + Exponential, 
 + Complex

In [159]:
#Trigonometric
arr = np.array([0,30,60,90,120,150,180])
print(arr,'\n')
print(np.sin(arr*np.pi/180))

[  0  30  60  90 120 150 180] 

[0.00000000e+00 5.00000000e-01 8.66025404e-01 1.00000000e+00
 8.66025404e-01 5.00000000e-01 1.22464680e-16]


In [161]:
print(np.cos(arr*np.pi/180))

[ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00]


In [163]:
print(np.tan(arr*np.pi/180))

[ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]


In [168]:
print(np.sinh(arr*np.pi/180))

[ 0.          0.54785347  1.24936705  2.3012989   3.99869134  6.8176233
 11.54873936]


In [171]:
print(np.cosh(arr*np.pi/180))

[ 1.          1.14023832  1.60028686  2.50917848  4.12183605  6.89057236
 11.59195328]


In [173]:
print(np.tanh(arr*np.pi/180))

[0.         0.48047278 0.78071444 0.91715234 0.97012382 0.98941321
 0.99627208]


In [177]:
import warnings
warnings.filterwarnings("ignore")
print(np.arcsin(arr*np.pi/180))
print(np.arccos(arr*np.pi/180))
print(np.arctan(arr*np.pi/180))

[0.         0.55106958        nan        nan        nan        nan
        nan]
[1.57079633 1.01972674        nan        nan        nan        nan
        nan]
[0.         0.48234791 0.80844879 1.00388482 1.12533883 1.20592739
 1.26262726]


In [192]:
#Rounding - round, floor, ceil
print(np.around(52.4765,1))
print(np.around(52.4))
print(np.floor(49.99056)) #Gives lowest value
print(np.ceil(67.09090)) #Gives Highest value

52.5
52.0
49.0
68.0


In [197]:
#Exponential
np.exp(1)

2.718281828459045

In [204]:
#Log
np.log(6)

1.791759469228055

In [209]:
np.log10(6) #With base

0.7781512503836436

In [212]:
#Complex - Real and Imaginery
arr = np.array([1+2j])
np.isreal(arr)

array([False])

In [217]:
arr = np.array([1+2])
np.isreal(arr)

array([ True])

In [219]:
#1+2j --> 1-2j
#conjugate
np.conj([1+2j])

array([1.-2.j])

## Numpy Linear Algebra
+ Matrix vector and products
+ Dot and vdot functions
+ Inner and outer functions
+ Matrix Functions
+ Matrix Eigenvalue functions

## Functions:
+ dot
+ vdot
+ inner
+ outer
+ matmul
+ det
+ solve
+ inv
+ trace
+ rank

In [318]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print("dot:",np.dot(x,y))
print("vdot:",np.dot(x,y))

dot: 70
vdot: 70


In [320]:
#In 2D
a = np.array([[1,2],[4,3]])    #1 2 | 6 7
b = np.array([[6,7],[5,8]])    #4 3 | 5 8
print("dot:\n",np.dot(a,b))
print("vdot: ",np.vdot(a,b))   #1x6+ 2x7+ 4x5 + 3x8

dot:
 [[16 23]
 [39 52]]
vdot:  64


In [326]:
#Inner and Outer element
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Inner:",np.inner(a,b))
print("Outer:\n",np.outer(a,b))
#Inner --> 1x4 + 2x5 + 3x6
#Outer --> 1xb, 2xb, 3xb

Inner: 32
Outer:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [330]:
a = np.array([[1,2],[4,3]])     #1 2 | 6 7
b = np.array([[6,7],[5,8]])     #4 3 | 5 8
print("Inner:\n",np.inner(a,b))
print("Outer:\n",np.outer(a,b)) #Inner --> 1x6 + 2x7 = 20; 1x5 + 2x8 = 21; 4x6 + 3x7 = 45; 4x5 + 3x8 = 44  

Inner:
 [[20 21]
 [45 44]]
Outer:
 [[ 6  7  5  8]
 [12 14 10 16]
 [24 28 20 32]
 [18 21 15 24]]


In [339]:
#Determinant
a = np.array([[1,2],[-3,4]])
print("Determinant:", np.linalg.det(a))
# --> 1x4 - (2x-3) = 4+6 = 10

Determinant: 10.000000000000002


In [349]:
#Inverse
a = np.array([[1,2],[3,4]])  # 1/|A| * adj(A) = 1 2 ----> adj ----> 4 -2
                                           #    3 4                -3  1
print("Inverse:\n",np.linalg.inv(a))

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [354]:
# eigen--> a - lambda(i) #i - identity matrix, a --> given matrix
#i = 1 0 
#    0 1 
a = np.array([[1,2],[3,4]])
print(np.linalg.eig(a))

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [362]:
#Rank Matrix
a = np.array([[2,24],[4,48]])
b = np.array([[1,2,3],[2,3,4],[3,5,7]])
print(a)
print(b)
print("Rank:",np.linalg.matrix_rank(a))
print("Rank:",np.linalg.matrix_rank(b))

[[ 2 24]
 [ 4 48]]
[[1 2 3]
 [2 3 4]
 [3 5 7]]
Rank: 1
Rank: 2


In [366]:
#Matrix Multiplication
x = np.array([1,2,3,4])
y = np.array([3,3,2,2])
print(np.dot(x,y)) #Same as matmul
print(np.matmul(x,y))

23
23


In [368]:
#Solve
a = np.array([[4,3],[-5,9]])
b = np.array([[20],[26]])
np.linalg.solve(a,b)

array([[2.],
       [4.]])

In [371]:
#Trace
a = np.array([[1,2],[3,4]]) #adds diagonally
print(np.trace(a))
b = np.array([[2,2],[3,6]])
print(np.trace(b))

5
8


### Broadcasting

In [376]:
arr = np.array([1,2,3])
arr1 = np.array([[4,5,6],[7,8,9]])
c = arr + 5 + arr1
c

array([[10, 12, 14],
       [13, 15, 17]])

### Statistics

In [378]:
a = np.array([1,2,3,4,5,6])
np.mean(a)

3.5

In [380]:
np.median(a)  #odd = n+1/2 ; even = ?

3.5

In [384]:
np.var(a)

2.9166666666666665

In [389]:
np.amin(a)

1

In [391]:
np.amax(a)

6

In [392]:
np.ptp(a) #max - min element and axis is also available here for wd and 3d

5

In [394]:
np.std(a)

1.707825127659933

In [401]:
a = np.array([1,2,3,4,5,6])
wt = np.array([1,3,5,4,3,6])
print(np.average(a, weights = wt)) #1x1 + 2x3 + 3x5 viceversa and finally, ans/1+3+5+4+3+6

4.045454545454546


### String Functions

In [6]:
#String operation
#string information
#string comparisons
#rjust, ljust, lower, upper, split, join, strip, capitalize, title, center, encode, decode
import numpy as np

In [10]:
#Lower and upper
a = 'Hello'
print(np.char.lower(a))
print(np.char.upper(a))

hello
HELLO


In [12]:
#Split
a = "Hello World"
np.char.split(a)

array(list(['Hello', 'World']), dtype=object)

In [20]:
#Join
a = ["Hello","World"]
print(np.char.join("-",a))
b = "Hello World"
print(np.char.join(" ",b))

['H-e-l-l-o' 'W-o-r-l-d']
H e l l o   W o r l d


In [23]:
#Capitalize
a = "hell"
np.char.capitalize(a)

array('Hell', dtype='<U4')

In [32]:
#Strip
a = "  Okay"
print(np.char.strip(a))

Okay


In [35]:
#Title -- Same like capitalize
a = "hell"
print(np.char.title(a))

Hell


In [44]:
#Center
a = "Help"
print(np.char.center(a,10,'😎'))

😎😎😎Help😎😎😎


In [83]:
a = ['chef','maid']
z = np.char.encode(a, encoding = 'utf8', errors = None) #cp037, cp500
print(z)

[b'chef' b'maid']


In [79]:
c = np.char.decode(z, encoding = 'utf8', errors = None)
print(c)

['chef' 'maid']


In [90]:
#ljust
arr = np.array(["a","b","c"])
width = 10
np.char.ljust(arr,width,fillchar = '*')

array(['a*********', 'b*********', 'c*********'], dtype='<U10')

In [98]:
#rjust
arr = np.array(["a","b","c"])
width = 10
print(np.char.rjust(arr,width,fillchar = '👻'))

['👻👻👻👻👻👻👻👻👻a' '👻👻👻👻👻👻👻👻👻b' '👻👻👻👻👻👻👻👻👻c']


In [100]:
#String Informations
#Count, find, rfind, isalpha, isdecimal, isdigit, islower, isupper, isspace, istitle

In [107]:
#Count
a = np.array(["SevenSeas"])
print(np.char.count(a,'S')) #No of 'S' is 2

[2]


In [109]:
#Find
print(np.char.find(a,'n')) #The place of n in the array is 4rth index

[4]


In [115]:
arr = np.array(['aaba','bba','as'])
print(np.char.find(arr, 'a'))
print(np.char.count(arr, 'a'))

[0 2 0]
[3 1 1]


In [120]:
print(np.char.rfind(arr,'a'))

[3 2 0]


In [124]:
arr = np.array(['1','-','3'])
np.char.isnumeric(arr)

array([ True, False,  True])

In [129]:
np.char.isdigit(arr) #Same like isnumeric

array([ True, False,  True])

In [138]:
arr = np.array(['aa','43','$'])
np.char.isalpha(arr)

array([ True, False, False])

In [141]:
arr = np.array(["1.0","1.78","1"])
np.char.isdecimal(arr)

array([False, False,  True])

In [145]:
np.char.islower('S')

array(False)

In [147]:
np.char.isupper('S')

array(True)

In [155]:
np.char.isspace(np.array(['S',' ','E']))

array([False,  True, False])

In [166]:
np.char.istitle(np.array(['Xyz','aBc', 'XYz', 'KraaL']))

array([ True, False, False, False])

In [172]:
#String comparison
print(np.char.equal('S','S'))

True


In [175]:
#String comparison #3 string is not possible
print(np.char.equal('Sww','S89'))

False


In [178]:
#String comparison
print(np.char.not_equal('S','S'))

False


In [181]:
print(np.char.not_equal('Sww','S89'))

True


In [184]:
print(np.char.greater('Saa','S')) #It checks the length i.e, saa > s

True


In [186]:
print(np.char.less('Saa','S')) # saa < s != True

False


In [192]:
print(np.char.less('Saw','Sbw'))
print(np.char.less('Saa','Saa'))

True
False


In [194]:
#greater_equal
print(np.char.greater_equal('Sa','Saa'))
print(np.char.greater_equal('Saa','Saa'))
print(np.char.greater_equal('Saa','Sa'))

False
True
True


In [195]:
#less_equal
print(np.char.less_equal('Saa','Saa'))
print(np.char.less_equal('S','Saa'))
print(np.char.less('Saaa','Saa'))

True
True
False
